### ISSUE TITLE
debloater

### ISSUE THREAD

**Issue by arsscriptum** [dtammam/PowerShell-Scripts#1]
Original debloater script: https://github.com/Sycnex/Windows10Debloater

**Comment by dtammam** [comment]
Absolutely right. Didn't realize this was being published, I'll de-list. Thank you.

**Comment by arsscriptum** [comment]
No worries mate :) So many scripts/code snippets exists and are being shared, one can't be blamed for using pre-existing stuff. I for one rarely start a new project from scratch. Good luck in you Powershell learning adventure. If I can be of some help if you have a question, don't hesitate to ask. guillaumeplante.qc@gmail.com https://github.com/arsscriptum/
