### ISSUE TITLE
SECURE CODE?!

### ISSUE THREAD

**Issue by Dalycode** [dtammam/PowerShell-Scripts#2]
Hello Sir, I have an issue with the following comment from your code.

"To run it securely, open an Administrative PowerShell terminal in the same directory as this script and run:
            powershell.exe -executionpolicy bypass -File .\PhoneNumberSanitizer.ps1 -file "*yourcsv*.csv" -newfile "*yournewcsv*.csv""

You should only be running trusted, signed code as secure in your environment.

Sign
Yo'
Scripts

**Comment by dtammam** [comment]
Ha, fair enough. I'll update the comment
